### ISSUE TITLE
Some request

### ISSUE THREAD

**Issue by LittleCutePM** [Mcbeany/Mcbeany#1]
Mmm can you make a sweet berries plugin?

**Comment by Mcbeany** [comment]
don't submit an issue here this is not my homepage

**Comment by LittleCutePM** [comment]
You can make?;-;

Pada tanggal Sel, 21 Sep 2021 23.19, Khang Nguyen ***@***.***>
menulis:

**Comment by Mcbeany** [comment]
i can

**Comment by LittleCutePM** [comment]
Please make it and thank you

Pada tanggal Sel, 21 Sep 2021 23.25, Khang Nguyen ***@***.***>
menulis:
